### ISSUE TITLE
Serbian church calendar: wrong leap year for negative date

### ISSUE THREAD

**Issue by yuanyelele** [Infrapink/calconv#7]
`abs(year) % 900 in (1, 601)` should be `abs(year) % 900 in (1, 501)`

https://github.com/Infrapink/calconv/blob/4d9b556f2eba7ce9a8a72feaf4f6391237b37a35/serbian_church.py#L58

**Comment by Infrapink** [comment]
Fixed via complete rewrite of the algorithms. Thanks for pointing that out.
